# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21179b42a063a688380a68ffded2cd9c195201f0bfc2f4190dd25b944b3a6324fea79f4b827091f0cfa7e2ca590bbc3c483b1f3409d5fb105dcc0a9e53e26c6c

test:
  secret_key_base: ec4f3105ca58687cab8f282730ac0c73a863ee10e5c62a9dd2faf35bae24ae7e2352ffeebf3cc16311bb63c4aaa0a485bb6fccc88cfef62fac64360279e16385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
